---
- name: Install MySQL server
  sudo: yes
  apt:  pkg=mysql-server state=latest

- name: Allow access to MySQL from anywhere
  sudo: yes
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" "line=#bind-address = 0.0.0.0"
  notify: restart mysql

- name: Add root user from anywhere to MySQL
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;"

- name: Create MySQL database symfony
  command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS symfony;"

#- name: Import MySQL databse
#  command: mysql --user=root --password= --default_character_set utf8 symfony < /var/www/database_core.sql

- name: Import the database
  mysql_db: name=symfony state=import target=/var/www/database_core.sql
  ignore_errors: true